on:
  push:

jobs:
  build:
    strategy:
      matrix:
        name: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    runs-on: ubuntu-latest

    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ matrix.name }}:latest

    steps:
      - run: docker pull alpine

      - run: docker tag alpine ${{ env.IMAGE }}

      - run: docker login https://docker.pkg.github.com -u token -p ${{ github.token }}

      - run: docker push ${{ env.IMAGE }}

      - run: docker image rm ${{ env.IMAGE }}

      - run: docker pull ${{ env.IMAGE }}
